

using IronPython.Hosting;
using Microsoft.Scripting.Hosting;
using System.Diagnostics;

var startingPath = @"C:\Users\abdul\Desktop\Capstone\ECE496-Capstone\src\cli\main.py";
var pythonPath = @"C:\Users\abdul\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\python3.7.exe";
var inputPath = @"C:\Users\abdul\Desktop\Capstone\TestFolder\SampleRateTest1_G.wav";
var outputPath = @"C:\Users\abdul\Desktop\Capstone\TestFolder\FinalVid.wav";
//ScriptEngine engine = Python.CreateEngine();
//engine.ExecuteFile(startingPath);


System.Diagnostics.ProcessStartInfo start = new System.Diagnostics.ProcessStartInfo();
start.FileName = pythonPath;

start.Arguments = string.Format("{0} -i {1} -o {2}", startingPath, inputPath, outputPath);
start.UseShellExecute = false;// Do not use OS shell
start.CreateNoWindow = true; // We don't need new window
start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)

Process p = new Process();
p.StartInfo = start;

p.Start();
string output = p.StandardOutput.ReadToEnd();
string error = p.StandardError.ReadToEnd();
p.WaitForExit();

Console.WriteLine("Output: " + output);
Console.WriteLine("Error: " + error);



